version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: taskdb
      DB_USER: taskuser
      DB_PASSWORD: taskpass
      JWT_SECRET: your_jwt_secret
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: your_smtp_user
      SMTP_PASS: your_smtp_pass
      SMTP_FROM: "Task App <no-reply@taskapp.com>"
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: 